import streamlit as st
from src.model_loader import load_caption_model, load_tokenizer, load_max_length
from src.image_preprocessor import extract_features
from src.caption_generator import generate_caption

st.set_page_config(page_title="Image Captioning", layout="centered")
st.title("Image Caption Generator")
st.write("Upload an image to get a caption generated by an AI model (ResNet50 + LSTM).")

uploaded_file = st.file_uploader("Upload Image", type=["jpg", "jpeg", "png"])

if uploaded_file:
    st.image(uploaded_file, caption="Uploaded Image", use_column_width=True)
    st.write("Generating caption...")

    # Load everything
    model = load_caption_model()
    tokenizer = load_tokenizer()
    max_length = load_max_length()

    # Feature Extraction
    features = extract_features(uploaded_file)

    # Caption Prediction
    caption = generate_caption(model, tokenizer, features, max_length)

    st.success("Generated Caption:")
    st.markdown(f"### {caption}")
